-- Create housekeeping_tasks table
CREATE TABLE IF NOT EXISTS housekeeping_tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    room_id INT NOT NULL,
    check_in_id INT,
    assigned_to INT,
    status ENUM('pending', 'in_progress', 'completed', 'cancelled') NOT NULL DEFAULT 'pending',
    priority ENUM('urgent', 'high', 'medium', 'low') NOT NULL DEFAULT 'medium',
    title VARCHAR(255) NOT NULL,
    description TEXT,
    notes TEXT,
    created_by INT NOT NULL,
    completed_by INT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME,
    started_at DATETIME,
    completed_at DATETIME,
    duration_minutes INT,
    FOREIGN KEY (room_id) REFERENCES rooms(id),
    FOREIGN KEY (check_in_id) REFERENCES check_ins(id),
    FOREIGN KEY (assigned_to) REFERENCES users(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (completed_by) REFERENCES users(id),
    INDEX idx_housekeeping_room (room_id),
    INDEX idx_housekeeping_status (status),
    INDEX idx_housekeeping_assigned (assigned_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create maintenance_tasks table
CREATE TABLE IF NOT EXISTS maintenance_tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    room_id INT NOT NULL,
    category ENUM('plumbing', 'electrical', 'hvac', 'furniture', 'appliance', 'building', 'other') NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    priority ENUM('urgent', 'high', 'medium', 'low') NOT NULL DEFAULT 'medium',
    status ENUM('pending', 'in_progress', 'completed', 'cancelled') NOT NULL DEFAULT 'pending',
    assigned_to INT,
    created_by INT NOT NULL,
    completed_by INT,
    notes TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME,
    started_at DATETIME,
    completed_at DATETIME,
    duration_minutes INT,
    FOREIGN KEY (room_id) REFERENCES rooms(id),
    FOREIGN KEY (assigned_to) REFERENCES users(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (completed_by) REFERENCES users(id),
    INDEX idx_maintenance_room (room_id),
    INDEX idx_maintenance_status (status),
    INDEX idx_maintenance_category (category),
    INDEX idx_maintenance_assigned (assigned_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
