"""Make maintenance task description optional

Revision ID: maintenance_desc_optional
Revises: add_photos_maintenance
Create Date: 2025-11-01 17:00:00.000000+07:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'maintenance_desc_optional'
down_revision: Union[str, None] = 'add_photos_maintenance'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance_tasks', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance_tasks', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
