"""add_total_spent_to_customers

Revision ID: 20251025_0933
Revises: b4a03c2e07c7
Create Date: 2025-10-25 09:33:00.000000+07:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251025_0933'
down_revision: Union[str, None] = '20251015_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'total_spent')
    # ### end Alembic commands ###
