"""add_payments_table_and_update_check_ins

Revision ID: b4a03c2e07c7
Revises: c5a5fd9ee03b
Create Date: 2025-10-14 10:07:12.195389+07:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a03c2e07c7'
down_revision: Union[str, None] = 'c5a5fd9ee03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_in_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_time', sa.DateTime(), nullable=False),
    sa.Column('payment_slip_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_ins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_check_in_id'), 'payments', ['check_in_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_time'), 'payments', ['payment_time'], unique=False)
    op.add_column('check_ins', sa.Column('number_of_guests', sa.Integer(), nullable=False))
    op.add_column('check_ins', sa.Column('is_overtime', sa.Integer(), nullable=False))
    op.add_column('check_ins', sa.Column('overtime_minutes', sa.Integer(), nullable=True))
    op.add_column('check_ins', sa.Column('overtime_charge', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_ins', 'overtime_charge')
    op.drop_column('check_ins', 'overtime_minutes')
    op.drop_column('check_ins', 'is_overtime')
    op.drop_column('check_ins', 'number_of_guests')
    op.drop_index(op.f('ix_payments_payment_time'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_check_in_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
